version: "v1"
project: "wordpress"
services:
  frontend:
    apache:
      image: "wordpress:4.7.1"
      instances: 1
      mem: 512
      domain: "$URI"
      port: 80
      env:
        - WORDPRESS_DB_HOST: "mysql.backend.wordpress"
        - WORDPRESS_DB_USER: "$DBUSER"
        - WORDPRESS_DB_PASSWORD: "$DBPASS"
      volumes:
        - path: "/var/www/html"
          size: "8GB"
      dependencies:
        - "../backend/mysql"
  backend:
    mysql:
      image: "mysql:8.0.0"
      instances: 1
      mem: 512
      env:
        - MYSQL_ROOT_PASSWORD: "$DBROOT"
        - MYSQL_USER: "$DBUSER"
        - MYSQL_PASSWORD: "$DBPASS"
        - MYSQL_DATABASE: "wordpress"
      volumes:
        - path: "/var/lib/mysql"
          size: "8GB"
